module.exports=(sequelize,DataTypes)=>{
const GroupMember=sequelize.define('GroupMember',{
    group_id:{
        type:DataTypes.INTEGER,
        primaryKey:true,
        references:{
            model:'Study_Groups',
            key:'group_id'
        }
    },
    user_id:{
        type:DataTypes.INTEGER,
        primaryKey:true,
        references:{
            model:'Users',
            key:'user_id'
        }
    },
    role:{
        type:DataTypes.ENUM('admin','membru'),
        defaultValue:'membru'
    },
    joined_at:{
        type:DataTypes.DATE,
        defaultValue:DataTypes.NOW
    }
},{
    tableName:'Group_Members',
    timestamps:false,
    underscored:true
})
return GroupMember;
}