module.exports=(sequelize,DataTypes)=>{
    const StudyGroup=sequelize.define('StudyGroup',{
        group_id:{
            type:DataTypes.INTEGER,
            primaryKey:true,
            autoIncrement:true
        },
        name:{
            type:DataTypes.STRING(100),
            allowNull:false
        },
        created_by:{
            type:DataTypes.INTEGER,
            allowNull:false,
            references:{
                model:'Users',
                key:'user_id'
            }
        },
        created_at:{
            type:DataTypes.DATE,
            defaultValue:DataTypes.NOW
        }
    },{
        tableName:'Study_Groups',
        timestamps:false,
        underscored:true
    });
    return StudyGroup;
}